apiVersion: v1
kind: Pod
metadata:
  name: hive
  labels:
    app: metastore
spec:
  containers:
    - name: hive
      image: spearframework/hive-metastore:2.1.1_v1.0
      ports:
        - containerPort: 5432
      envFrom:
        secretRef:
          name: hive-creds
      volumeMounts:
        - name: postgres-vol
          mountPath: /var/lib/postgresql
  volumes:
    - name: postgres-vol
      hostPath:
        path: /home/postgres/vol
        type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: metastore-hive
spec:
  selector:
    app: metastore
  ports:
    - port: 5432
---
apiVersion: v1
kind: Pod
metadata:
  name: spark-with-hadoop
spec:
  containers:
    - name: hadoop-spark-with-hive
      image: spearframework/spark-with-hive-hadoop-hive:2.4.7_v1.0
      ports:
        - containerPort: 4040
        - containerPort: 4041
        - containerPort: 8089
      command: ["/usr/sbin/init"]
      securityContext:
        privileged: true








