apiVersion: v1
kind: Pod
metadata:
 name: postgres
 labels:
   tier: db-tier
spec:
 containers:
   - name: postgres
     image: postgres
     ports:
     - containerPort: 5432
     env:
        - name: POSTGRES_USER
          value: postgres_user
        - name: POSTGRES_PASSWORD
          value: mysecretpassword
     volumeMounts:
       - name: postgres-vol
         mountPath: /var/lib/postgresql
 volumes:
    - name: postgres-vol
      hostPath:
        path: /home/postgres/vol
        type: DirectoryOrCreate